const assert=require('assert');
const IO=require('./js/map/map_io');
const Doors=require('./js/map/doors');
const MapRenderer=require('./js/map/map_renderer');
const base=require('./js/map/map_data');
const file=IO.snapshot(base);
assert(file.floorLayers.some(f=>f.id==='service_middle'),'central floor must be directly editable');
const floor=file.floorLayers.find(f=>f.id==='service_middle');
floor.polygon[0].x-=35;floor.type='wood_parquet';
const restored=IO.materialize(JSON.parse(JSON.stringify(file)),base,Doors);
assert.deepEqual(restored.floorLayers,file.floorLayers);
assert.deepEqual(restored.walls,base.walls.map((w,i)=>({...w,id:w.id||'walls_'+String(i+1).padStart(3,'0')})));
const bad={...floor,polygon:[{x:0,y:0},{x:40,y:40},{x:0,y:40},{x:40,y:0}]};
assert(!IO.validate({...file,floorLayers:[bad]}).ok,'self crossing floor must be rejected');
assert(!IO.validate({...file,floorLayers:[floor,floor]}).ok,'duplicate floor ids must be rejected');
assert(!IO.validate({...file,floorLayers:[{...floor,type:'unknown'}]}).ok);
const renderer=Object.create(MapRenderer.prototype);
renderer.mapData={...restored,floorLayers:[floor]};
renderer.floorPatterns={carpet_grey:'grey',wood_parquet:'wood'};
const fills=[];let clips=0;
const ctx={save(){},restore(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},clip(){clips++;},createPattern:p=>p,fill(){fills.push(this.fillStyle);}};
renderer.renderFloorZones(ctx);renderer.renderCoreMass(ctx);
assert.deepEqual(fills,['grey','wood'],'legacy core, zones and office fixtures must not repaint an edited floor');
assert.equal(clips,1,'editable floor coverage must stay inside building footprint');
renderer.mapData.floorLayers=[];fills.length=0;renderer.renderFloorZones(ctx);renderer.renderCoreMass(ctx);
assert.deepEqual(fills,['grey'],'deleting all floor overlays must not resurrect the legacy layers');
console.log('Floor migration, roundtrip, polygon validation, rendering priority and deletion passed');
