'use strict';
const assert = require('node:assert/strict');
const { webcrypto } = require('node:crypto');
(async () => {
  const p = await import('./js/network/protocol.js');
  const { InputFrames, RemoteInputSource } = await import('./js/network/remote_input.js');
  const f = {version:1,seq:1,x:1,y:-1,angle:Math.PI,buttons:1,edges:[1,0,0]};
  const decoded = p.decodeInput(p.encodeInput(f));
  assert.equal(decoded.seq,1); assert(Math.abs(decoded.angle-Math.PI)<1e-6);
  for (const change of [{version:2},{seq:-1},{x:2},{y:NaN},{angle:Infinity},{buttons:128},{edges:[1,2]},{edges:[-1,0,0]}]) assert.equal(p.validateInput({...f,...change}),false);
  assert.equal(p.decodeInput(new Uint8Array(31)),null); assert.equal(p.decodeInput('abc'),null);
  const remote = new RemoteInputSource(); assert(remote.receive(f,0)); assert(remote.isAttackJustPressed()); remote.clearFrameTriggers();
  assert(!remote.receive(f,.01)); remote.receive({...f,seq:4},.02); assert(!remote.isAttackJustPressed());
  remote.receive({...f,seq:6,edges:[2,1,1]},.03); assert(remote.isAttackJustPressed()); assert(remote.isExecuteJustPressed()); assert(remote.isThrowOrPickupJustPressed());
  assert(Math.hypot(remote.getMovementVector().x,remote.getMovementVector().y)<=1.000001);
  remote.expire(.4); assert.equal(remote.getMovementVector().length,0); assert(!remote.isAttackDown()); assert(!remote.isAttackJustPressed());
  const frames=new InputFrames(), input={getMovementVector:()=>({x:3,y:-4}),getAimAngle:()=>20,isAttackDown:()=>true,isAttackJustPressed:()=>true,isThrowOrPickupJustPressed:()=>false,isExecuteJustPressed:()=>false};
  assert(p.validateInput(frames.capture(input,{x:0,y:0}))); assert.equal(frames.capture(input,{x:0,y:0},true).buttons,0);
  const s={version:1,seq:1,time:1,wave:1,remaining:5,phase:'PREWAVE',timer:3,players:[{id:0,x:0,y:0,angle:3.1,isAlive:true}],enemies:[],bullets:[],floor:[],thrown:[],doors:[],glass:[],crates:[]};
  assert.deepEqual(p.decodeSnapshot(p.encodeSnapshot(s)),s);
  for(const change of [{version:2},{phase:'HACK'},{players:[{id:7,x:0,y:0,isAlive:true}]},{players:[{id:0,x:NaN,y:0,isAlive:true}]},{enemies:[{id:1,x:1,execute:'evil'}]},{enemies:[{id:1},{id:1}]},{bullets:Array.from({length:513},(_,id)=>({id}))}]) assert(!p.validateSnapshot({...s,...change}));
  assert.equal(p.decodeSnapshot(new TextEncoder().encode('{bad')),null);
  assert.equal(p.decodeSnapshot(new Uint8Array(256001)),null);
  const telegraph={id:0,x:300,y:500,angle:0,countdown:1.2,blocked:true};
  assert(p.validateSnapshot({...s,telegraphs:[telegraph]}));
  for(const bad of [{...telegraph,x:Infinity},{...telegraph,countdown:-1},{...telegraph,blocked:'yes'}])assert(!p.validateSnapshot({...s,telegraphs:[bad]}));
  const buffer=new p.SnapshotBuffer(.1); buffer.push(s,1); buffer.push({...s,seq:2,players:[{...s.players[0],x:100,angle:-3.1}]},1.1);
  const mid=buffer.sample(1.15).players[0]; assert(Math.abs(mid.x-50)<1e-9); assert(Math.abs(Math.abs(mid.angle)-Math.PI)<.05);
  assert(!buffer.push(s,2));
  const execution=new p.SnapshotBuffer(.1);
  execution.push({...s,players:[{...s.players[0],state:'EXECUTING',executionTimer:.2}]},1);
  execution.push({...s,seq:2,players:[{...s.players[0],state:'EXECUTING',executionTimer:.25}]},1.05);
  assert(Math.abs(execution.sample(1.125).players[0].executionTimer-.225)<1e-9,'execution pose interpolates between network ticks');
  execution.push({...s,seq:3,players:[{...s.players[0],state:'IDLE',executionTimer:0}]},1.1);
  assert.equal(execution.sample(1.175).players[0].executionTimer,0,'completed execution cannot smear into the next state');
  const a=await p.fingerprint({b:[2,3],a:1},webcrypto.subtle), b=await p.fingerprint({a:1,b:[2,3]},webcrypto.subtle);
  assert.equal(a,b); assert.notEqual(a,await p.fingerprint({a:2,b:[2,3]},webcrypto.subtle));
  assert(p.validateHello({version:1,ruleset:p.RULESET,role:'HOST',nonce:'a'.repeat(32),fingerprint:a}));
  assert(!p.validateHello({version:1,role:'HOST',nonce:'a'.repeat(32),fingerprint:a}),'old instant-death clients cannot join a rescue mission');
  assert(!p.validateHello({version:2,role:'CLIENT',nonce:'a'.repeat(32),fingerprint:a}));
  console.log('PASS bounded protocol, invalid frames, edge retransmission, stale inputs, interpolation and SHA-256');
})().catch(e=>{console.error(e);process.exit(1);});
