const assert=require('assert');
const IO=require('./js/map/map_io');
const base=require('./js/map/map_data');
const Doors=require('./js/map/doors');
const before=JSON.stringify(base);
const payload=IO.snapshot(base);
assert(IO.validate(payload).ok);
assert.equal(payload.version,2);
payload.props=payload.props.filter(p=>p.id!=='ambient_sofa');
payload.walls.splice(0,1);
const loaded=IO.materialize(payload,base,Doors);
assert.equal(loaded.walls.length,base.walls.length-1);
assert(!loaded.props.some(p=>p.id==='ambient_sofa'),'deleted decoration must not reappear');
assert(loaded.doors[0] instanceof Doors.Door);
loaded.doors[0].shattered=true;
loaded.glassPartitions[0].shattered=true;
const again=IO.materialize(IO.snapshot(loaded),base,Doors);
assert(!again.doors[0].shattered && !again.glassPartitions[0].shattered,'runtime damage must not enter map exports');
const old={version:1,format:payload.format,...Object.fromEntries(['walls','doors','glassPartitions','props'].map(k=>[k,payload[k]]))};
const migrated=IO.materialize(old,base,Doors);
assert.deepEqual(migrated.playerSpawn,base.playerSpawn);
assert.deepEqual(migrated.zones,base.zones);
assert.equal(JSON.stringify(base),before,'map IO must not mutate authored source');
assert(!IO.validate({...payload,version:99}).ok);
assert(!IO.validate({...payload,props:[{id:'bad',x:NaN,y:0,width:1,height:1}]}).ok);
assert(!IO.validate({...payload,walls:[payload.walls[0],payload.walls[0]]}).ok);
assert(!IO.validate({...payload,buildingFootprint:[{x:0,y:0}]}).ok);
console.log('Map format v1/v2, isolated loading, runtime reset and validation passed');
