const assert=require('node:assert/strict');
global.CONFIG=require('./js/config');
const data=new Map();global.localStorage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};
const {GameHUD}=require('./js/ui/hud'),{ScoreScreen}=require('./js/ui/score_screen');
const hud=new GameHUD();for(let i=0;i<5;i++)hud.addKillScore('GUN',400,0,0);
const points=CONFIG.SCORING.COMBO_MULTIPLIERS.slice(0,5).reduce((a,m)=>a+400*m,0);assert.equal(hud.currentScore,points);
hud.update(20);assert.equal(hud.comboCount,0);assert.equal(hud.maxComboRecorded,5);hud.reset();assert.equal(hud.maxComboRecorded,0);
const screen=new ScoreScreen();assert.deepEqual(screen.leaderboard,[]);
const run={runId:'empty',score:0,totalKills:0,weaponsUsed:new Set(),elapsedTime:0,waveReached:1,maxCombo:0};screen.show('GAME_OVER',run);assert.equal(screen.breakdown.totalCalculatedScore,0);screen.show('GAME_OVER',run);assert.equal(screen.leaderboard.length,1);
screen.show('GAME_OVER',{...run,runId:'real',score:5000,totalKills:10,meleeKills:2,gunKills:6,throwKills:2,executions:1,doorSlams:1,weaponsUsed:new Set(['BAT','UZI']),waveReached:4,wavesCleared:3,elapsedTime:120,maxCombo:5});
assert.equal(screen.stats.waveReached,4);assert.equal(screen.breakdown.timeBonus,1200);assert.equal(screen.breakdown.flexibilityScore,2500);assert.equal(screen.breakdown.carnageScore,1600);assert.equal(screen.breakdown.boldnessScore,5500);assert.equal(screen.breakdown.totalCalculatedScore,15800);
assert.equal(new ScoreScreen().leaderboard[0].score,15800);
for(let i=0;i<12;i++)screen.show('GAME_OVER',{...run,runId:'r'+i,score:i});assert.equal(screen.leaderboard.length,8);
data.set(screen.LEADERBOARD_KEY,'{}');assert.deepEqual(screen.loadLeaderboard(),[]);data.set(screen.LEADERBOARD_KEY,'{');assert.deepEqual(screen.loadLeaderboard(),[]);
data.set(screen.LEADERBOARD_KEY,JSON.stringify([{score:'bad',runId:'x'},null]));assert.deepEqual(screen.loadLeaderboard(),[]);
console.log('PASS combos persist/reset, exact scoring, empty run, waves, bonuses, deduplication, top eight, persistence and corrupt storage');

// Presentation events must never modify scoring, combo decay, or ammunition.
const visual=new GameHUD();
visual.setWave(2,7);visual.update(.12);
assert.equal(visual.waveImpact,0);
visual.update(3,{wave:2,enemiesRemaining:7});
visual.setWave(2,7);assert(visual.waveAge>3,'same-wave sync cannot replay the announcement');
visual.setWave(3,9);assert.equal(visual.waveAge,0);assert.equal(visual.waveImpact,.1);
const gun={id:'PISTOL',name:'Pistol',isGun:true,maxAmmo:12};
visual.setWeapon(gun,1);visual.setWeapon(gun,0);assert.equal(visual.ammoImpact,.1);
visual.update(.12);visual.setWeapon(gun,0);assert.equal(visual.ammoImpact,0,'empty HUD sync stays still');
visual.addKillScore('GUN',400,0,0);
const state={score:visual.currentScore,combo:visual.comboCount,timer:visual.comboTimer};
visual.notifyDryFire();assert.equal(visual.ammoImpact,.1);
assert.deepEqual({score:visual.currentScore,combo:visual.comboCount,timer:visual.comboTimer},state);
assert.equal(visual.currentAmmo,0);
visual.update(.12);
assert.equal(visual.scoreImpact,0);assert.equal(visual.comboImpact,0);assert.equal(visual.ammoImpact,0);
assert.equal(visual.comboTimer,state.timer-.12,'presentation does not change combo decay');
visual.setWeapon({name:'Bat',isGun:false});visual.notifyDryFire();assert.equal(visual.ammoImpact,0);
visual.addKillScore('GUN',400,0,0);
const slowTimer=visual.comboTimer;
visual.update(.01,null,.1);
assert.equal(visual.scoreImpact,0,'100 ms impact uses real time during hit stop');
assert.equal(visual.comboTimer,slowTimer-.01,'combo still uses simulation time');
visual.reset();assert.equal(visual.maskAge,0);assert.equal(visual.presentedWave,null);
console.log('PASS event-only HUD impacts, repeated wave sync, dry fire isolation and reset');
