'use strict';
const assert=require('node:assert/strict');
const Player=require('./js/entities/player'),Enemy=require('./js/entities/enemy');
const {InputManager}=require('./js/engine/input'),{NavGraph}=require('./js/engine/pathfinding'),{Door}=require('./js/map/doors');
(async()=>{
  const {prepareRevives,advanceRevives,reviveTarget,squadDefeated,respawnSquad,rankPlayers}=await import('./js/network/coop_logic.js');
  const {InputFrames,RemoteInputSource}=await import('./js/network/remote_input.js');
  const {record,encodeSnapshot,decodeSnapshot,SnapshotBuffer}=await import('./js/network/protocol.js');
  const make=(id,x=0)=>Object.assign(new Player(x,0,'vincent'),{playerId:id,coopEnabled:true});
  const solo=new Player();solo.takeHit();assert(!solo.isAlive,'solo retains instant death');
  const down=make(0),helper=make(1,35),other=make(2,40),squad=[down,helper,other];
  down.equipWeapon('PISTOL',7);const retainedAmmo=down.ammo;down.burstRemaining=3;down.takeHit();
  assert(down.isAlive&&down.isDowned);assert.equal(down.state,'DOWNED');assert.equal(down.downedTimer,25);
  down.takeHit();assert.equal(down.downedTimer,25);assert.equal(down.burstRemaining,0);
  assert.equal(down.attack(100,0),null);assert.equal(down.throwWeapon(100,0),null);
  const movement={getMovementVector:()=>({x:1,y:0,length:1}),getAimAngle:()=>0};
  for(let i=0;i<60;i++)down.update(1/60,movement,[],[],[],[],null,null,false);
  assert(down.x>40&&down.x<50,'crawl is 22% of ordinary speed');assert.equal(down.state,'DOWNED');
  assert.equal(down.downedTimer,25,'neither entity update nor client prediction advances bleeding');
  down.x=0;
  const held=new Set([1]),inputFor=id=>({isReviveDown:()=>held.has(id)}),clear=()=>true;
  const step=(dt=1/60,reach=clear)=>advanceRevives(squad,prepareRevives(squad,inputFor,reach),dt);
  for(let i=0;i<60;i++)step();assert(Math.abs(down.reviveProgress-1)<1e-8);assert(helper.isReviving);
  assert.equal(helper.throwWeapon(100,0),null,'rescue reserves the pickup/throw action');
  held.clear();step();assert.equal(down.reviveProgress,0);assert.equal(down.reviverId,-1);
  held.add(1);for(let i=0;i<30;i++)step();helper.x=100;step();assert.equal(down.reviveProgress,0,'walking away interrupts rescue');
  helper.x=35;for(let i=0;i<30;i++)step();step(1/60,()=>false);assert.equal(down.reviveProgress,0,'closing cover interrupts rescue');
  held.add(2);for(let i=0;i<119;i++)step();assert(down.isDowned,'two helpers cannot accelerate the two-second hold');
  assert.equal(down.reviverId,1);const completed=step();assert.equal(completed.revived.length,1);
  assert(!down.isDowned&&down.isAlive&&down.isInvulnerable);assert.equal(down.respawnShield,.8);
  assert.equal(down.ammo,retainedAmmo);assert.equal(down.currentWeapon.id,'PISTOL');assert.equal(helper.revives,1);assert(!other.revives);
  down.takeHit();assert(!down.isDowned,'revive protection prevents instant knockdown');
  down._finishExecution();assert(down.isInvulnerable,'an interrupted execution cannot cancel remaining revive protection');
  down.isInvulnerable=false;down.takeHit();held.clear();
  for(let i=0;i<1499;i++)step();assert(down.isDowned&&down.downedTimer>0);
  step();assert(!down.isAlive&&!down.isDowned);assert.equal(down.state,'DEAD');
  assert(!squadDefeated(squad));helper.takeHit();other.takeHit();assert(squadDefeated(squad),'downed/dead squad loses immediately');
  const rows=rankPlayers(squad,new Map());assert(rows.every(r=>!r.isAlive),'downed players are not marked as survivors in existing results');
  const points=[{x:0,y:0},{x:34,y:0},{x:68,y:0}];respawnSquad(squad,points);
  assert(squad.every(p=>p.isAlive&&!p.isDowned&&p.state==='IDLE'));assert.equal(down.currentWeapon.id,'MAGNUM');

  down.isInvulnerable=false;down.takeHit();helper.isInvulnerable=false;other.isInvulnerable=false;
  down.downedTimer=.01;down.reviveProgress=1.99;down.reviverId=1;held.add(1);step();assert(!down.isAlive,'bleeding deadline wins a simultaneous rescue');
  down.respawn(0,0);down.takeHit();for(let i=0;i<30;i++)step();helper.takeHit();step();assert.equal(down.reviveProgress,0,'incapacitated helper cannot finish');
  helper.revive();other.x=40;held.clear();held.add(2);step();assert.equal(down.reviverId,2);assert(down.reviveProgress<.02);
  advanceRevives([down,helper],prepareRevives([down,helper],inputFor,clear),1/60);assert.equal(down.reviveProgress,0,'departed helper cancels progress');

  const wallMap={walls:[{x1:20,y1:-80,x2:20,y2:80}],doors:[],glassPartitions:[],props:[],rooms:[]};
  const graph=new NavGraph(wallMap),reach=(a,b)=>graph.canTraverse(a,b,4,false);helper.x=40;
  assert.equal(reviveTarget(helper,squad,reach),null,'cannot rescue through a wall');
  wallMap.walls=[];wallMap.doors=[new Door({x:20,y:-35,length:70,baseAngle:Math.PI/2})];
  assert.equal(reviveTarget(helper,squad,reach),null,'cannot rescue through a closed door');
  wallMap.doors[0].shattered=true;assert.equal(reviveTarget(helper,squad,reach),down);
  const enemy=new Enemy(0,0);enemy._checkLineOfSightToPlayer=()=>true;
  assert.equal(enemy.selectPlayer([down,helper],[]),helper,'AI skips the closest downed colleague');

  const input=new InputManager();input._onKeyDown({code:'KeyE',preventDefault(){}});assert(input.isReviveDown());
  const frames=new InputFrames(),remote=new RemoteInputSource();remote.receive(frames.capture(input,helper),0);assert(remote.isReviveDown());
  remote.clearFrameTriggers();assert(remote.isReviveDown(),'revive is held state, not a repeated edge');
  remote.expire(.3);assert(!remote.isReviveDown(),'lost inputs release the rescue within 250 ms');
  assert.equal(frames.capture(input,down).buttons,0);assert.equal(frames.capture(input,helper,true).buttons,0);
  input._onKeyUp({code:'KeyE'});input._onKeyDown({code:'Space',preventDefault(){}});assert(input.isReviveDown());input._onKeyUp({code:'Space'});
  input.gamepad.connected=true;input.gamepad.buttonA=true;assert(input.isReviveDown());input.gamepad.buttonA=false;input.gamepad.buttonX=true;assert(input.isReviveDown());
  const snapshot={version:1,seq:1,time:1,wave:1,remaining:5,phase:'PREWAVE',timer:3,players:[record({...down,id:0})],enemies:[],bullets:[],floor:[],thrown:[],doors:[],glass:[],crates:[]};
  assert.deepEqual(decodeSnapshot(encodeSnapshot(snapshot)),snapshot);
  const buffer=new SnapshotBuffer(.1);buffer.push(snapshot,1);
  buffer.push({...snapshot,seq:2,players:[{...snapshot.players[0],isDowned:false,state:'IDLE',x:20,downedTimer:0,reviveProgress:0,reviverId:-1}]},1.05);
  assert(!buffer.sample(1.125).players[0].isDowned,'revival is immediate, not blended with the crawling pose');
  console.log('PASS solo preservation, crawl, 25s bleeding, continuous 2s rescue, cover, contention, interruption, gamepad, snapshots, defeat and respawn');
})().catch(e=>{console.error(e);process.exit(1);});
