const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const Physics = require('./js/engine/physics.js');
const { Door } = require('./js/map/doors.js');
const stub = { getContext: () => ({}) };
const env = { Physics, document: {readyState:'loading',addEventListener(){},getElementById:()=>stub,createElement:()=>stub}, window:{addEventListener(){}},performance:{now:()=>0},module:{exports:{}} };
vm.runInNewContext(fs.readFileSync('./js/main.js','utf8'),env);
const reachable = env.module.exports.canReachTarget;
const a={x:0,y:0},b={x:40,y:0};
assert(reachable(a,b,{}),'open floor allows interactions');
assert(!reachable(a,b,{walls:[{x1:20,y1:-30,x2:20,y2:30}]}),'solid partition blocks close-range interactions');
const glass={x1:20,y1:-30,x2:20,y2:30,shattered:false};
assert(!reachable(a,b,{glassPartitions:[glass]}),'intact glass blocks interactions');
glass.shattered=true;
assert(reachable(a,b,{glassPartitions:[glass]}),'broken glass allows interactions');
const door={x:20,y:-30,angle:Math.PI/2,length:60};
assert(!reachable(a,b,{doors:[door]}),'closed door blocks interactions');
door.angle=0;
assert(reachable(a,b,{doors:[door]}),'open doorway allows interactions');
assert(!reachable(null,b,{}),'missing actor is rejected');

global.CONFIG=require('./js/config.js');
const {WaveSpawner}=require('./js/entities/spawner.js');
const spawner=new WaveSpawner();
spawner.spawnPoints=[{id:'occupied',x:0,y:0},{id:'clear',x:500,y:0}];
spawner.start('richard',{x:0,y:0});
assert(spawner.spawnQueue.every(e=>e.spawnPoint.id==='clear'),'new wave never selects occupied starting entrance');
assert(spawner.getSpawnTelegraphs().every(p=>p.id==='clear'),'warnings agree with safe entrances');
const spawned=[];spawner.onEnemySpawned=e=>spawned.push(e);
for(let i=0;i<240;i++)spawner.update(1/60,{x:500,y:0},spawned.length);
if (!spawned.length) spawner.update(1/60,{x:500,y:0},0);
assert(spawned.every(e=>e.x===500&&e.y===0),'announced entrance does not silently move with player');
console.log('Interaction obstruction and initial ingress spacing passed');
const Player=require('./js/entities/player.js');
assert.equal(new Player(0,0,'RICHARD').attack(30,0).isLethal,false,'ordinary fists knock down');
assert.equal(new Player(0,0,'TONY').attack(30,0).isLethal,true,'Tony retains lethal punches');
const armed=new Player(0,0,'DENNIS');
assert.equal(armed.attack(30,0).isLethal,true,'knife remains lethal');
